server:
  port: 8087

spring:
  application:
    name: api-gateway-api-spring-boot
  cloud:
    gateway:
      routes:
        - id: inventario
          uri: http://localhost:8081
          predicates:
            - Path=/inventario/**
